version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: ./services/postgres
    ports:
      - "5432:5432"
    env_file:
      - ./services/postgres/.env

  # mailer:
  #   build: ./services/mailer
  #   ports:
  #     - "3001:3001"
