version: '3'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    build: ./postgres
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    restart: always

  mailer:
    build: ./mailer
    ports:
      - "3001:3001"
    restart: always
