# Use an official Postgres runtime as a parent image
FROM postgres:13-alpine

# Set the environment variables for the Postgres database
ENV POSTGRES_USER fanrik
ENV POSTGRES_PASSWORD fanrik123
ENV POSTGRES_DB mydatabase

# Expose port 5432 for the database to listen on
EXPOSE 5432
